version: "3.1"
services:
    www:
        build: ./docker
        ports:
            - "${WWW_PORT}:80"
        volumes:
            - ./:/var/www/html/
        links:
            - mariadb5
        networks:
            - default
    mariadb5:
        image: mariadb:5.5.56
        ports:
            - "3310:3306"
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - mariadb5:/var/lib/mysql
    myadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mariadb5:db
        ports:
            - ${MY_ADMIN_PORT}:80
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
volumes:
    mariadb5: